### ISSUE TITLE
A file listed in the Manifest could not be found

### ISSUE THREAD

**Issue by TechieAndroid** [spikyatlinux/ebuilds_for_gentoo#3]
Sorry if this is something simple, I'm pretty new to ebuilds and overlays.

![image](https://user-images.githubusercontent.com/17918163/106966422-e688f000-670a-11eb-9387-7a288e37ee4a.png)

**Comment by spikyatlinux** [comment]
Hey,

I´ve copied the ebuild from src_prepare-overlay, you´ll find the config here [https://data.gpo.zugaina.org/src_prepare-overlay/src_prepare-overlay.conf](url). If you want to add it to your overlay try 

> wget https://data.gpo.zugaina.org/src_prepare-overlay/src_prepare-overlay.conf -O /etc/portage/repos.conf/src_prepare-overlay.conf && emaint sync -r src_prepare-overlay

If you have any issues please contact the puplisher of the anbox ebuild.

Best regards
