### ISSUE TITLE
pdlib problems

### ISSUE THREAD

**Issue by fr3ddy-sudo** [spikyatlinux/ebuilds_for_gentoo#5]
Hi,  i get folloing error 

`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdlib.so' (tried: /usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so (/usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so: undefined symbol: DGifOpenFileName), /usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so.so (/usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

do you have any idea to solf it?

Thanks Freddy

**Comment by spikyatlinux** [comment]
Hi, didn´t use it long time ago, I´m using dev-php/pecl-imagick as replacement. 
The giflib library isn't being linked during the build process. Don´t know howto solve this. pdlib depends on media-libs/giflib which should be installed. I think need to write a patch, if i found some time.

Need some time to test and try, if I´m not as busy as now. 

Regards

**Comment by spikyatlinux** [comment]
Okay I´ve tried and hopefully adapted ebuild. 

```
ldd /usr/lib64/php8*/lib/extensions/no-debug-zts-*/pdlib.so | grep -i gif
	libgif.so.7 => /usr/lib64/libgif.so.7 (0x00007fd6adbe0000)
	libgif.so.7 => /usr/lib64/libgif.so.7 (0x00007f0f46b3f000)
```

```
php -m | grep pdlib 
pdlib
```

On my testing system error is gone for php-8.2 and php-8.3.

Perhaps give me short feedback if error is gone for you,too. Then I can close this issue.

Merry christmas

**Comment by spikyatlinux** [comment]
Perhaps give me short feedback if error is gone for you,too. Then I can close this issue.
Regards

**Comment by fr3ddy-sudo** [comment]
Hi thanks for your work, but now i get a other error

`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdlib.so' (tried: /usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so (/usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so: undefined symbol: _ZN4dlib3cpu11tensor_convclEbRNS_16resizable_tensorERKNS_6tensorES6_S6_b), /usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so.so (/usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

maybe you have an idea?

Merry christmas you 2

**Comment by spikyatlinux** [comment]
```
cat package.accept_keywords/pdlib
=sci-libs/dlib-19.24.2 ~amd64
=dev-libs/cudnn-8.8.0.121 ~amd64
=dev-util/nvidia-cuda-toolkit-12.4.0 ~amd64
```
These have I installed, perhaps recompile them first, then try again. 

`emerge -1 sci-libs/dlib dev-libs/cudnn dev-util/nvidia-cuda-toolkit media-libs/giflib`

 Check your php.ini for typo pdlib.so.so should be pdlib.so

**Comment by fr3ddy-sudo** [comment]
the error is the same after recompile :(

php 8.2 and php8.3 same error

**Comment by fr3ddy-sudo** [comment]
i think iknow my problem

` cmake  --help-policy CMP0146
CMP0146
-------

.. versionadded:: 3.27

The ``FindCUDA`` module is removed.

The ``FindCUDA`` module has been deprecated since CMake 3.10.
CMake 3.27 and above prefer to not provide the module.
This policy provides compatibility for projects that have not been
ported away from it.

Projects using the ``FindCUDA`` module should be updated to use
CMake's first-class ``CUDA`` language support.  List ``CUDA`` among the
languages named in the top-level call to the ``project()`` command,
or call the ``enable_language()`` command with ``CUDA``.
Then one can add CUDA (``.cu``) sources directly to targets,
similar to other languages.

The ``OLD`` behavior of this policy is for ``find_package(CUDA)`` to
load the deprecated module.  The ``NEW`` behavior is for uses of the
module to fail as if it does not exist.

This policy was introduced in CMake version 3.27.
It may be set by ``cmake_policy()`` or ``cmake_minimum_required()``.
If it is not set, CMake warns, and uses ``OLD`` behavior.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.
`

**Comment by spikyatlinux** [comment]
`/usr/lib64/php8.2/lib/extensions/no-debug-non-zts-20220829/pdlib.so.so` is strange, mine is under 

```
/usr/lib64/php8.3/lib/extensions/no-debug-zts-20230831/pdlib.so
/usr/lib64/php8.2/lib/extensions/no-debug-zts-20220829/pdlib.so
```
Perhaps uninstall with `emerge -vC dev-php/pdlib` then search for wrong, old or obsolete entries under /etc/php

`grep -ir pdlib.so /etc/php/*` remove or edit those entries, then try to reinstall `emerge -av "=dev-php/pdlib-1.1.0-r3"`

Sometimes ago I had also naming issue pdlib.so.so, which should be pdlib.so,but don´t know how I had solve this. 

My cmake version is `dev-build/cmake-3.30.6` which works fine on my system.

**In a clean environment with the following use flags, there are no errors also.**

```
dev-lang/php exif gd xpm
sci-libs/dlib gif jpeg png
```
Adapt/edit to adjust your needs. If this didn´t work also. Have some nice days.
Close for now, cause error is gone on my sys. Give me short feedback.
